// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aopckpsxjnzlorocwswi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFvcGNrcHN4am56bG9yb2N3c3dpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3OTMyMzgsImV4cCI6MjA2ODM2OTIzOH0.r9jJC9qkzxl1Gy_dgW4YQlaNeC1MwYgV4QvzLVin-KU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});